
project_id = "zgcsgwlggvjvvshhhcmb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
enabled = true
# Ensure functions can access secrets
[functions.customer-portal]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true
